name: f1_project
description: "A new Flutter project."
publish_to: "none"

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  postgres: ^3.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/f1_logo.svg
    - assets/podium.png
    - assets/logos/mclaren.png
    - assets/logos/astonmartin.png
    - assets/logos/alpine.png
    - assets/logos/ferrari.png
    - assets/logos/mercedes.png
    - assets/logos/redbull.png
    - assets/logos/haas.png
    - assets/logos/racingbulls.png
    - assets/logos/kicksauber.png
    - assets/logos/williams.png
