name: f1_project
description: "A new Flutter project."
publish_to: "none"
1.0.0+4

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flame: ^1.32.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.10.0
  logger: ^2.6.1
  path_drawing: ^1.0.1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
  postgres: ^3.5.6
  svg_path_parser: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1



flutter_launcher_icons:
  android: true
  ios: true
  image_path: "web/icons/Icon-512.png"
  windows:
    generate: true
    image_path: "web/icons/Icon-512.png"
  web:
    generate: true
    image_path: "web/icons/Icon-512.png"
    background_color: "#FAFAFA"
    theme_color: "#E10600"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FAFAFA"          # colore sfondo
  image: assets/f1_logo.png   # logo personalizzato
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:

    - assets/f1_logo.svg
    - assets/f1_logo.png
    - assets/podium.png
    - assets/logos/mclaren.png
    - assets/logos/mclaren_swoosh.png
    - assets/logos/astonmartin.png
    - assets/logos/alpine.png
    - assets/logos/ferrari.png
    - assets/logos/mercedes.png
    - assets/logos/redbull.png
    - assets/logos/haas.png
    - assets/logos/racingbulls.png
    - assets/logos/kicksauber.png
    - assets/logos/williams.png
    - assets/logos/bar.png
    - assets/logos/brawn.png
    - assets/logos/honda.png
    - assets/logos/tyrrell.png
    - assets/logos/lotus.png
    - assets/logos/benetton.png
    - assets/logos/renault.png
    - assets/logos/toleman.png
    - assets/logos/minardi.png
    - assets/logos/tororosso.png
    - assets/logos/alphatauri.png
    - assets/logos/jordan.png
    - assets/logos/midland.png
    - assets/logos/spyker.png
    - assets/logos/forceindia.png
    - assets/logos/racingpoint.png
    - assets/logos/stewart.png
    - assets/logos/jaguar.png
    - assets/logos/sauber.png
    - assets/logos/bmw.png
    - assets/logos/alfaromeo.png
    - assets/logos/RedBullDash.png
    - assets/logos/McLarenDash.png
    - assets/logos/AlpineDash.png
    - assets/logos/AstonMartinDash.png

    - assets/macchine/mclaren.png
    - assets/macchine/astonmartin.png
    - assets/macchine/alpine.png
    - assets/macchine/ferrari.png
    - assets/macchine/mercedes.png
    - assets/macchine/redbull.png
    - assets/macchine/haas.png
    - assets/macchine/racingbulls.png
    - assets/macchine/kicksauber.png
    - assets/macchine/williams.png

    - assets/piloti/norris.png
    - assets/piloti/alonso.png
    - assets/piloti/ocon.png
    - assets/piloti/leclerc.png
    - assets/piloti/sainz.png
    - assets/piloti/hamilton.png
    - assets/piloti/russell.png
    - assets/piloti/verstappen.png
    - assets/piloti/tsunoda.png
    - assets/piloti/bortoleto.png
    - assets/piloti/colapinto.png
    - assets/piloti/gasly.png
    - assets/piloti/piastri.png
    - assets/piloti/antonelli.png
    - assets/piloti/bearman.png
    - assets/piloti/hadjar.png
    - assets/piloti/hulkenberg.png
    - assets/piloti/lawson.png
    - assets/piloti/stroll.png
    - assets/piloti/albon.png

    - assets/circuiti/
    - assets/circuiti/abudhabi.svg
    - assets/circuiti/australia.svg
    - assets/circuiti/austria.svg
    - assets/circuiti/azerbaijan.svg
    - assets/circuiti/bahrain.svg
    - assets/circuiti/belgium.svg
    - assets/circuiti/brazil.svg
    - assets/circuiti/canada.svg
    - assets/circuiti/greatbritain.svg
    - assets/circuiti/hungary.svg
    - assets/circuiti/italyimola.svg
    - assets/circuiti/italymonza.svg
    - assets/circuiti/japan.svg
    - assets/circuiti/mexico.svg
    - assets/circuiti/monaco.svg
    - assets/circuiti/netherlands.svg
    - assets/circuiti/qatar.svg
    - assets/circuiti/saudiarabia.svg
    - assets/circuiti/shanghai.svg
    - assets/circuiti/singapore.svg
    - assets/circuiti/spain.svg
    - assets/circuiti/usacota.svg
    - assets/circuiti/usamiami.svg
    - assets/circuiti/usavegas.svg
    - assets/circuiti/mask/abudhabi_mask.png
    - assets/circuiti/mask/australia_mask.png
    - assets/circuiti/mask/austria_mask.png
    - assets/circuiti/mask/bahrain_mask.png
    - assets/circuiti/mask/belgium_mask.png
    - assets/circuiti/mask/brazil_mask.png
    - assets/circuiti/mask/canada_mask.png
    - assets/circuiti/mask/greatbritain_mask.png
    - assets/circuiti/mask/hungary_mask.png
    - assets/circuiti/mask/italyimola_mask.png
    - assets/circuiti/mask/italymonza_mask.png
    - assets/circuiti/mask/mexico_mask.png
    - assets/circuiti/mask/netherlands_mask.png
    - assets/circuiti/mask/qatar_mask.png
    - assets/circuiti/mask/shanghai_mask.png
    - assets/circuiti/mask/singapore_mask.png
    - assets/circuiti/mask/spain_mask.png
    - assets/circuiti/mask/usacota_mask.png
    - assets/circuiti/mask/usamiami_mask.png
    - assets/circuiti/mask/usavegas_mask.png

    - assets/circuiti/track/abudhabi_track.json
    - assets/circuiti/track/australia_track.json
    - assets/circuiti/track/austria_track.json
    - assets/circuiti/track/azerbaijan_track.json
    - assets/circuiti/track/bahrain_track.json
    - assets/circuiti/track/belgium_track.json
    - assets/circuiti/track/brazil_track.json
    - assets/circuiti/track/canada_track.json
    - assets/circuiti/track/greatbritain_track.json
    - assets/circuiti/track/hungary_track.json
    - assets/circuiti/track/italyimola_track.json
    - assets/circuiti/track/italymonza_track.json
    - assets/circuiti/track/japan_track.json
    - assets/circuiti/track/mexico_track.json
    - assets/circuiti/track/monaco_track.json
    - assets/circuiti/track/netherlands_track.json
    - assets/circuiti/track/qatar_track.json
    - assets/circuiti/track/saudiarabia_track.json
    - assets/circuiti/track/shanghai_track.json
    - assets/circuiti/track/singapore_track.json
    - assets/circuiti/track/spain_track.json
    - assets/circuiti/track/usacota_track.json
    - assets/circuiti/track/usamiami_track.json
    - assets/circuiti/track/usavegas_track.json
