name: f1_project
description: "A new Flutter project."
publish_to: "none"

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/f1_logo.svg
    - assets/podium.png
    - assets/logos/mclaren.png
    - assets/logos/astonmartin.png
    - assets/logos/alpine.png
    - assets/logos/ferrari.png
    - assets/logos/mercedes.png
    - assets/logos/redbull.png
    - assets/logos/haas.png
    - assets/logos/racingbulls.png
    - assets/logos/kicksauber.png
    - assets/logos/williams.png
    - assets/logos/bar.png
    - assets/logos/brawn.png
    - assets/logos/honda.png
    - assets/logos/tyrrell.png
    - assets/logos/lotus.png
    - assets/logos/benetton.png
    - assets/logos/renault.png
    - assets/logos/toleman.png
    - assets/logos/minardi.png
    - assets/logos/tororosso.png
    - assets/logos/alphatauri.png
    - assets/logos/jordan.png
    - assets/logos/midland.png
    - assets/logos/spyker.png
    - assets/logos/forceindia.png
    - assets/logos/racingpoint.png
    - assets/logos/stewart.png
    - assets/logos/jaguar.png
    - assets/logos/sauber.png
    - assets/logos/bmw.png
    - assets/logos/alfaromeo.png

    - assets/macchine/mclaren.png
    - assets/macchine/astonmartin.png
    - assets/macchine/alpine.png
    - assets/macchine/ferrari.png
    - assets/macchine/mercedes.png
    - assets/macchine/redbull.png
    - assets/macchine/haas.png
    - assets/macchine/racingbulls.png
    - assets/macchine/kicksauber.png
    - assets/macchine/williams.png

    - assets/piloti/norris.png
    - assets/piloti/alonso.png
    - assets/piloti/ocon.png
    - assets/piloti/leclerc.png
    - assets/piloti/sainz.png
    - assets/piloti/hamilton.png
    - assets/piloti/russell.png
    - assets/piloti/verstappen.png
    - assets/piloti/tsunoda.png
    - assets/piloti/bortoleto.png
    - assets/piloti/colapinto.png
    - assets/piloti/gasly.png
    - assets/piloti/piastri.png
    - assets/piloti/antonelli.png
    - assets/piloti/bearman.png
    - assets/piloti/hadjar.png
    - assets/piloti/hulkenberg.png
    - assets/piloti/lawson.png
    - assets/piloti/stroll.png
    - assets/piloti/albon.png