// lib/game/models/circuit.dart
class Circuit {
  final String id;
  final String displayName;
  final String svgPath;
  final String maskPath;
  final double xPercentage;
  final double yPercentage;
  final String trackJsonPath;
  final double viewBoxX;
  final double viewBoxY;
  final double viewBoxWidth;
  final double viewBoxHeight;

  const Circuit({
    required this.id,
    required this.displayName,
    required this.svgPath,
    required this.maskPath,
    required this.xPercentage,
    required this.yPercentage,
    required this.trackJsonPath,
    required this.viewBoxX,
    required this.viewBoxY,
    required this.viewBoxWidth,
    required this.viewBoxHeight,
  });
}

const List<Circuit> allCircuits = [
  Circuit(
    id: 'abudhabi',
    displayName: 'Abu Dhabi',
    svgPath: 'assets/circuiti/abudhabi.svg',
    maskPath: 'assets/circuiti/mask/abudhabi_mask.png',
    xPercentage: 0.44,
    yPercentage: 0.47,
    trackJsonPath: 'assets/circuiti/track/abudhabi_track.json',
    viewBoxX: 10,
    viewBoxY: 75,
    viewBoxWidth: 260,
    viewBoxHeight: 131,
  ),
  Circuit(
    id: 'australia',
    displayName: 'Australia',
    svgPath: 'assets/circuiti/australia.svg',
    maskPath: 'assets/circuiti/mask/australia_mask.png',
    xPercentage: 0.695,
    yPercentage: 0.916,
    trackJsonPath: 'assets/circuiti/track/australia_track.json',
    viewBoxX: 10,
    viewBoxY: 56,
    viewBoxWidth: 266,
    viewBoxHeight: 142,
  ),
  Circuit(
    id: 'austria',
    displayName: 'Austria',
    svgPath: 'assets/circuiti/austria.svg',
    maskPath: 'assets/circuiti/mask/austria_mask.png',
    xPercentage: 0.711,
    yPercentage: 0.831,
    trackJsonPath: 'assets/circuiti/track/austria_track.json',
    viewBoxX: 9,
    viewBoxY: 52,
    viewBoxWidth: 262,
    viewBoxHeight: 173,
  ),
  Circuit(
    id: 'azerbaijan',
    displayName: 'Azerbaijan',
    svgPath: 'assets/circuiti/azerbaijan.svg',
    maskPath: 'assets/circuiti/mask/azerbaijan_mask.png',
    xPercentage: 0.80,
    yPercentage: 0.35,
    trackJsonPath: 'assets/circuiti/track/azerbaijan_track.json',
    viewBoxX: 8,
    viewBoxY: 53,
    viewBoxWidth: 264,
    viewBoxHeight: 173,
  ),
  Circuit(
    id: 'bahrain',
    displayName: 'Bahrain',
    svgPath: 'assets/circuiti/bahrain.svg',
    maskPath: 'assets/circuiti/mask/bahrain_mask.png',
    xPercentage: 0.64,
    yPercentage: 0.93,
    trackJsonPath: 'assets/circuiti/track/bahrain_track.json',
    viewBoxX: 10,
    viewBoxY: 38,
    viewBoxWidth: 265,
    viewBoxHeight: 185,
  ),
  Circuit(
    id: 'belgium',
    displayName: 'Belgio',
    svgPath: 'assets/circuiti/belgium.svg',
    maskPath: 'assets/circuiti/mask/belgium_mask.png',
    xPercentage: 0.138,
    yPercentage: 0.708,
    trackJsonPath: 'assets/circuiti/track/belgium_track.json',
    viewBoxX: 9,
    viewBoxY: 54,
    viewBoxWidth: 262,
    viewBoxHeight: 171,
  ),
  Circuit(
    id: 'brazil',
    displayName: 'Brasile',
    svgPath: 'assets/circuiti/brazil.svg',
    maskPath: 'assets/circuiti/mask/brazil_mask.png',
    xPercentage: 0.315,
    yPercentage: 0.254,
    trackJsonPath: 'assets/circuiti/track/brazil_track.json',
    viewBoxX: 6,
    viewBoxY: 52,
    viewBoxWidth: 267,
    viewBoxHeight: 177,
  ),
  Circuit(
    id: 'canada',
    displayName: 'Canada',
    svgPath: 'assets/circuiti/canada.svg',
    maskPath: 'assets/circuiti/mask/canada_mask.png',
    xPercentage: 0.217,
    yPercentage: 0.800,
    trackJsonPath: 'assets/circuiti/track/canada_track.json',
    viewBoxX: 5,
    viewBoxY: 50,
    viewBoxWidth: 268,
    viewBoxHeight: 183,
  ),
  Circuit(
    id: 'greatbritain',
    displayName: 'Gran Bretagna',
    svgPath: 'assets/circuiti/greatbritain.svg',
    maskPath: 'assets/circuiti/mask/greatbritain_mask.png',
    xPercentage: 0.615,
    yPercentage: 0.866,
    trackJsonPath: 'assets/circuiti/track/greatbritain_track.json',
    viewBoxX: 8,
    viewBoxY: 49,
    viewBoxWidth: 264,
    viewBoxHeight: 186,
  ),
  Circuit(
    id: 'hungary',
    displayName: 'Ungheria',
    svgPath: 'assets/circuiti/hungary.svg',
    maskPath: 'assets/circuiti/mask/hungary_mask.png',
    xPercentage: 0.71,
    yPercentage: 0.95,
    trackJsonPath: 'assets/circuiti/track/hungary_track.json',
    viewBoxX: 35,
    viewBoxY: 30,
    viewBoxWidth: 211,
    viewBoxHeight: 219,
  ),
  Circuit(
    id: 'italyimola',
    displayName: 'Imola',
    svgPath: 'assets/circuiti/italyimola.svg',
    maskPath: 'assets/circuiti/mask/italyimola_mask.png',
    xPercentage: 0.692,
    yPercentage: 0.181,
    trackJsonPath: 'assets/circuiti/track/italyimola_track.json',
    viewBoxX: 10,
    viewBoxY: 71,
    viewBoxWidth: 260,
    viewBoxHeight: 155,
  ),
  Circuit(
    id: 'italymonza',
    displayName: 'Monza',
    svgPath: 'assets/circuiti/italymonza.svg',
    maskPath: 'assets/circuiti/mask/italymonza_mask.png',
    xPercentage: 0.805,
    yPercentage: 0.938,
    trackJsonPath: 'assets/circuiti/track/italymonza_track.json',
    viewBoxX: 9,
    viewBoxY: 57,
    viewBoxWidth: 262,
    viewBoxHeight: 163,
  ),
  Circuit(
    id: 'japan',
    displayName: 'Giappone',
    svgPath: 'assets/circuiti/japan.svg',
    maskPath: 'assets/circuiti/mask/japan_mask.png',
    xPercentage: 0.35,
    yPercentage: 0.93,
    trackJsonPath: 'assets/circuiti/track/japan_track.json',
    viewBoxX: 9,
    viewBoxY: 67,
    viewBoxWidth: 262,
    viewBoxHeight: 145,
  ),
  Circuit(
    id: 'mexico',
    displayName: 'Messico',
    svgPath: 'assets/circuiti/mexico.svg',
    maskPath: 'assets/circuiti/mask/mexico_mask.png',
    xPercentage: 0.115,
    yPercentage: 0.618,
    trackJsonPath: 'assets/circuiti/track/mexico_track.json',
    viewBoxX: 10,
    viewBoxY: 58,
    viewBoxWidth: 260,
    viewBoxHeight: 165,
  ),
  Circuit(
    id: 'monaco',
    displayName: 'Monaco',
    svgPath: 'assets/circuiti/monaco.svg',
    maskPath: 'assets/circuiti/mask/monaco_mask.png',
    xPercentage: 0.0725,
    yPercentage: 0.559,
    trackJsonPath: 'assets/circuiti/track/monaco_track.json',
    viewBoxX: 11,
    viewBoxY: 60,
    viewBoxWidth: 262,
    viewBoxHeight: 179,
  ),
  Circuit(
    id: 'netherlands',
    displayName: 'Olanda',
    svgPath: 'assets/circuiti/netherlands.svg',
    maskPath: 'assets/circuiti/mask/netherlands_mask.png',
    xPercentage: 0.095,
    yPercentage: 0.583,
    trackJsonPath: 'assets/circuiti/track/netherlands_track.json',
    viewBoxX: 9,
    viewBoxY: 23,
    viewBoxWidth: 262,
    viewBoxHeight: 235,
  ),
  Circuit(
    id: 'qatar',
    displayName: 'Qatar',
    svgPath: 'assets/circuiti/qatar.svg',
    maskPath: 'assets/circuiti/mask/qatar_mask.png',
    xPercentage: 0.70,
    yPercentage: 0.95,
    trackJsonPath: 'assets/circuiti/track/qatar_track.json',
    viewBoxX: 7,
    viewBoxY: 38,
    viewBoxWidth: 267,
    viewBoxHeight: 203,
  ),
  Circuit(
    id: 'saudiarabia',
    displayName: 'Arabia Saudita',
    svgPath: 'assets/circuiti/saudiarabia.svg',
    maskPath: 'assets/circuiti/mask/saudiarabia_mask.png',
    xPercentage: 0.808,
    yPercentage: 0.205,
    trackJsonPath: 'assets/circuiti/track/saudiarabia_track.json',
    viewBoxX: 10,
    viewBoxY: 47,
    viewBoxWidth: 260,
    viewBoxHeight: 185,
  ),
  Circuit(
    id: 'shanghai',
    displayName: 'Cina',
    svgPath: 'assets/circuiti/shanghai.svg',
    maskPath: 'assets/circuiti/mask/shanghai_mask.png',
    xPercentage: 0.31,
    yPercentage: 0.79,
    trackJsonPath: 'assets/circuiti/track/shanghai_track.json',
    viewBoxX: 9,
    viewBoxY: 53,
    viewBoxWidth: 262,
    viewBoxHeight: 174,
  ),
  Circuit(
    id: 'singapore',
    displayName: 'Singapore',
    svgPath: 'assets/circuiti/singapore.svg',
    maskPath: 'assets/circuiti/mask/singapore_mask.png',
    xPercentage: 0.953,
    yPercentage: 0.533,
    trackJsonPath: 'assets/circuiti/track/singapore_track.json',
    viewBoxX: 13,
    viewBoxY: 56,
    viewBoxWidth: 254,
    viewBoxHeight: 167,
  ),
  Circuit(
    id: 'spain',
    displayName: 'Spagna',
    svgPath: 'assets/circuiti/spain.svg',
    maskPath: 'assets/circuiti/mask/spain_mask.png',
    xPercentage: 0.66,
    yPercentage: 0.87,
    trackJsonPath: 'assets/circuiti/track/spain_track.json',
    viewBoxX: 5,
    viewBoxY: 92,
    viewBoxWidth: 273,
    viewBoxHeight: 95,
  ),
  Circuit(
    id: 'usacota',
    displayName: 'USA',
    svgPath: 'assets/circuiti/usacota.svg',
    maskPath: 'assets/circuiti/mask/usacota_mask.png',
    xPercentage: 0.094,
    yPercentage: 0.628,
    trackJsonPath: 'assets/circuiti/track/usacota_track.json',
    viewBoxX: 7,
    viewBoxY: 57,
    viewBoxWidth: 267,
    viewBoxHeight: 164,
  ),
  Circuit(
    id: 'usamiami',
    displayName: 'Miami',
    svgPath: 'assets/circuiti/usamiami.svg',
    maskPath: 'assets/circuiti/mask/usamiami_mask.png',
    xPercentage: 0.47,
    yPercentage: 0.29,
    trackJsonPath: 'assets/circuiti/track/usamiami_track.json',
    viewBoxX: 7,
    viewBoxY: 81,
    viewBoxWidth: 268,
    viewBoxHeight: 119,
  ),
  Circuit(
    id: 'usavegas',
    displayName: 'Las Vegas',
    svgPath: 'assets/circuiti/usavegas.svg',
    maskPath: 'assets/circuiti/mask/usavegas_mask.png',
    xPercentage: 0.89,
    yPercentage: 0.19,
    trackJsonPath: 'assets/circuiti/track/usavegas_track.json',
    viewBoxX: 10,
    viewBoxY: 60,
    viewBoxWidth: 260,
    viewBoxHeight: 161,
  ),
];
