// lib/game/models/circuit.dart
class Circuit {
  final String id;
  final String displayName;
  final String svgPath;
  final String maskPath;
  final double xPercentage;
  final double yPercentage;

  const Circuit({
    required this.id,
    required this.displayName,
    required this.svgPath,
    required this.maskPath,
    required this.xPercentage,
    required this.yPercentage,
  });
}

const List<Circuit> allCircuits = [
  Circuit(
    id: 'abudhabi',
    displayName: 'Abudhabi',
    svgPath: 'assets/circuiti/abudhabi.svg',
    maskPath: 'assets/circuiti/abudhabi_mask.png',
    xPercentage: 0.44,
    yPercentage: 0.47,
  ),
  Circuit(
    id: 'australia',
    displayName: 'Australia',
    svgPath: 'assets/circuiti/australia.svg',
    maskPath: 'assets/circuiti/australia_mask.png',
    xPercentage: 0.695,
    yPercentage: 0.916,
  ),
  Circuit(
    id: 'austria',
    displayName: 'Austria',
    svgPath: 'assets/circuiti/austria.svg',
    maskPath: 'assets/circuiti/austria_mask.png',
    xPercentage: 0.711,
    yPercentage: 0.831,
  ),
  // Circuit(
  //   id: 'azerbaijan',
  //   displayName: 'Azerbaijan',
  //   svgPath: 'assets/circuiti/azerbaijan.svg',
  //   maskPath: 'assets/circuiti/azerbaijan_mask.png',
  //   xPercentage: 0.80,
  //   yPercentage: 0.35,
  // ),
  Circuit(
    id: 'bahrain',
    displayName: 'Bahrain',
    svgPath: 'assets/circuiti/bahrain.svg',
    maskPath: 'assets/circuiti/bahrain_mask.png',
    xPercentage: 0.64,
    yPercentage: 0.93,
  ),
  Circuit(
    id: 'belgium',
    displayName: 'Belgium',
    svgPath: 'assets/circuiti/belgium.svg',
    maskPath: 'assets/circuiti/belgium_mask.png',
    xPercentage: 0.138,
    yPercentage: 0.708,
  ),
  Circuit(
    id: 'brazil',
    displayName: 'Brazil',
    svgPath: 'assets/circuiti/brazil.svg',
    maskPath: 'assets/circuiti/brazil_mask.png',
    xPercentage: 0.315,
    yPercentage: 0.254,
  ),
  Circuit(
    id: 'canada',
    displayName: 'Canada',
    svgPath: 'assets/circuiti/canada.svg',
    maskPath: 'assets/circuiti/canada_mask.png',
    xPercentage: 0.217,
    yPercentage: 0.800,
  ),
  Circuit(
    id: 'greatbritain',
    displayName: 'Great Britain',
    svgPath: 'assets/circuiti/greatbritain.svg',
    maskPath: 'assets/circuiti/greatbritain_mask.png',
    xPercentage: 0.615,
    yPercentage: 0.866,
  ),
  Circuit(
    id: 'hungary',
    displayName: 'Hungary',
    svgPath: 'assets/circuiti/hungary.svg',
    maskPath: 'assets/circuiti/hungary_mask.png',
    xPercentage: 0.71,
    yPercentage: 0.95,
  ),
  Circuit(
    id: 'italyimola',
    displayName: 'Italy Imola',
    svgPath: 'assets/circuiti/italyimola.svg',
    maskPath: 'assets/circuiti/italyimola_mask.png',
    xPercentage: 0.692,
    yPercentage: 0.181,
  ),
  Circuit(
    id: 'italymonza',
    displayName: 'Italy Monza',
    svgPath: 'assets/circuiti/italymonza.svg',
    maskPath: 'assets/circuiti/italymonza_mask.png',
    xPercentage: 0.805,
    yPercentage: 0.938,
  ),
  // Circuit(
  //   id: 'japan',
  //   displayName: 'Japan',
  //   svgPath: 'assets/circuiti/japan.svg',
  //   maskPath: 'assets/circuiti/japan_mask.png',
  //   xPercentage: 0.35,
  //   yPercentage: 0.93,
  // ),
  Circuit(
    id: 'mexico',
    displayName: 'Mexico',
    svgPath: 'assets/circuiti/mexico.svg',
    maskPath: 'assets/circuiti/mexico_mask.png',
    xPercentage: 0.115,
    yPercentage: 0.618,
  ),
  // Circuit(
  //   id: 'monaco',
  //   displayName: 'Monaco',
  //   svgPath: 'assets/circuiti/monaco.svg',
  //   maskPath: 'assets/circuiti/monaco_mask.png',
  //   xPercentage: 0.0725,
  //   yPercentage: 0.559,
  // ),
  Circuit(
    id: 'netherlands',
    displayName: 'Netherlands',
    svgPath: 'assets/circuiti/netherlands.svg',
    maskPath: 'assets/circuiti/netherlands_mask.png',
    xPercentage: 0.095,
    yPercentage: 0.583,
  ),
  Circuit(
    id: 'qatar',
    displayName: 'Qatar',
    svgPath: 'assets/circuiti/qatar.svg',
    maskPath: 'assets/circuiti/qatar_mask.png',
    xPercentage: 0.70,
    yPercentage: 0.95,
  ),
  // Circuit(
  //   id: 'saudiarabia',
  //   displayName: 'Saudi Arabia',
  //   svgPath: 'assets/circuiti/saudiarabia.svg',
  //   maskPath: 'assets/circuiti/saudiarabia_mask.png',
  //   xPercentage: 0.808,
  //   yPercentage: 0.205,
  // ),
  Circuit(
    id: 'shanghai',
    displayName: 'Shanghai',
    svgPath: 'assets/circuiti/shanghai.svg',
    maskPath: 'assets/circuiti/shanghai_mask.png',
    xPercentage: 0.31,
    yPercentage: 0.79,
  ),
  Circuit(
    id: 'singapore',
    displayName: 'Singapore',
    svgPath: 'assets/circuiti/singapore.svg',
    maskPath: 'assets/circuiti/singapore_mask.png',
    xPercentage: 0.953,
    yPercentage: 0.533,
  ),
  Circuit(
    id: 'spain',
    displayName: 'Spain',
    svgPath: 'assets/circuiti/spain.svg',
    maskPath: 'assets/circuiti/spain_mask.png',
    xPercentage: 0.66,
    yPercentage: 0.87,
  ),
  Circuit(
    id: 'usacota',
    displayName: 'USA Cota',
    svgPath: 'assets/circuiti/usacota.svg',
    maskPath: 'assets/circuiti/usacota_mask.png',
    xPercentage: 0.094,
    yPercentage: 0.628,
  ),
  Circuit(
    id: 'usamiami',
    displayName: 'USA Miami',
    svgPath: 'assets/circuiti/usamiami.svg',
    maskPath: 'assets/circuiti/usamiami_mask.png',
    xPercentage: 0.47,
    yPercentage: 0.29,
  ),
  Circuit(
    id: 'usavegas',
    displayName: 'USA Vegas',
    svgPath: 'assets/circuiti/usavegas.svg',
    maskPath: 'assets/circuiti/usavegas_mask.png',
    xPercentage: 0.89,
    yPercentage: 0.19,
  ),
];
