// lib/game/models/circuit.dart
class Circuit {
  final String id;
  final String displayName;
  final String svgPath;
  final String maskPath;
  final double xPercentage;
  final double yPercentage;

  const Circuit({
    required this.id,
    required this.displayName,
    required this.svgPath,
    required this.maskPath,
    required this.xPercentage,
    required this.yPercentage,
  });
}

const List<Circuit> allCircuits = [
  Circuit(
    id: 'abudhabi',
    displayName: 'Abudhabi',
    svgPath: 'assets/circuiti/abudhabi.svg',
    maskPath: 'assets/circuiti/abudhabi_mask.png',
    xPercentage: 0.44,
    yPercentage: 0.47,
  ),
  Circuit(
    id: 'australia',
    displayName: 'Australia',
    svgPath: 'assets/circuiti/australia.svg',
    maskPath: 'assets/circuiti/australia_mask.png',
    xPercentage: 0.35,
    yPercentage: 0.75,
  ),
  Circuit(
    id: 'austria',
    displayName: 'Austria',
    svgPath: 'assets/circuiti/austria.svg',
    maskPath: 'assets/circuiti/austria_mask.png',
    xPercentage: 0.6,
    yPercentage: 0.6,
  ),
  Circuit(
    id: 'azerbaijan',
    displayName: 'Azerbaijan',
    svgPath: 'assets/circuiti/azerbaijan.svg',
    maskPath: 'assets/circuiti/azerbaijan_mask.png',
    xPercentage: 0.7,
    yPercentage: 0.4,
  ),
  Circuit(
    id: 'bahrain',
    displayName: 'Bahrain',
    svgPath: 'assets/circuiti/bahrain.svg',
    maskPath: 'assets/circuiti/bahrain_mask.png',
    xPercentage: 0.5,
    yPercentage: 0.5,
  ),
  Circuit(
    id: 'belgium',
    displayName: 'Belgium',
    svgPath: 'assets/circuiti/belgium.svg',
    maskPath: 'assets/circuiti/belgium_mask.png',
    xPercentage: 0.4,
    yPercentage: 0.3,
  ),
  Circuit(
    id: 'brazil',
    displayName: 'Brazil',
    svgPath: 'assets/circuiti/brazil.svg',
    maskPath: 'assets/circuiti/brazil_mask.png',
    xPercentage: 0.3,
    yPercentage: 0.8,
  ),
  Circuit(
    id: 'canada',
    displayName: 'Canada',
    svgPath: 'assets/circuiti/canada.svg',
    maskPath: 'assets/circuiti/canada_mask.png',
    xPercentage: 0.3,
    yPercentage: 0.2,
  ),
  Circuit(
    id: 'greatbritain',
    displayName: 'Great Britain',
    svgPath: 'assets/circuiti/greatbritain.svg',
    maskPath: 'assets/circuiti/greatbritain_mask.png',
    xPercentage: 0.4,
    yPercentage: 0.4,
  ),
  Circuit(
    id: 'hungary',
    displayName: 'Hungary',
    svgPath: 'assets/circuiti/hungary.svg',
    maskPath: 'assets/circuiti/hungary_mask.png',
    xPercentage: 0.5,
    yPercentage: 0.6,
  ),
  Circuit(
    id: 'italyimola',
    displayName: 'Italy Imola',
    svgPath: 'assets/circuiti/italyimola.svg',
    maskPath: 'assets/circuiti/italyimola_mask.png',
    xPercentage: 0.55,
    yPercentage: 0.65,
  ),
  Circuit(
    id: 'italymonza',
    displayName: 'Italy Monza',
    svgPath: 'assets/circuiti/italymonza.svg',
    maskPath: 'assets/circuiti/italymonza_mask.png',
    xPercentage: 0.55,
    yPercentage: 0.65,
  ),
  Circuit(
    id: 'japan',
    displayName: 'Japan',
    svgPath: 'assets/circuiti/japan.svg',
    maskPath: 'assets/circuiti/japan_mask.png',
    xPercentage: 0.9,
    yPercentage: 0.4,
  ),
  Circuit(
    id: 'mexico',
    displayName: 'Mexico',
    svgPath: 'assets/circuiti/mexico.svg',
    maskPath: 'assets/circuiti/mexico_mask.png',
    xPercentage: 0.3,
    yPercentage: 0.4,
  ),
  Circuit(
    id: 'monaco',
    displayName: 'Monaco',
    svgPath: 'assets/circuiti/monaco.svg',
    maskPath: 'assets/circuiti/monaco_mask.png',
    xPercentage: 0.45,
    yPercentage: 0.5,
  ),
  Circuit(
    id: 'netherlands',
    displayName: 'Netherlands',
    svgPath: 'assets/circuiti/netherlands.svg',
    maskPath: 'assets/circuiti/netherlands_mask.png',
    xPercentage: 0.4,
    yPercentage: 0.4,
  ),
  Circuit(
    id: 'qatar',
    displayName: 'Qatar',
    svgPath: 'assets/circuiti/qatar.svg',
    maskPath: 'assets/circuiti/qatar_mask.png',
    xPercentage: 0.6,
    yPercentage: 0.6,
  ),
  Circuit(
    id: 'saudiarabia',
    displayName: 'Saudi Arabia',
    svgPath: 'assets/circuiti/saudiarabia.svg',
    maskPath: 'assets/circuiti/saudiarabia_mask.png',
    xPercentage: 0.6,
    yPercentage: 0.5,
  ),
  Circuit(
    id: 'shanghai',
    displayName: 'Shanghai',
    svgPath: 'assets/circuiti/shanghai.svg',
    maskPath: 'assets/circuiti/shanghai_mask.png',
    xPercentage: 0.8,
    yPercentage: 0.4,
  ),
  Circuit(
    id: 'singapore',
    displayName: 'Singapore',
    svgPath: 'assets/circuiti/singapore.svg',
    maskPath: 'assets/circuiti/singapore_mask.png',
    xPercentage: 0.75,
    yPercentage: 0.55,
  ),
  Circuit(
    id: 'spain',
    displayName: 'Spain',
    svgPath: 'assets/circuiti/spain.svg',
    maskPath: 'assets/circuiti/spain_mask.png',
    xPercentage: 0.45,
    yPercentage: 0.5,
  ),
  Circuit(
    id: 'usacota',
    displayName: 'USA Cota',
    svgPath: 'assets/circuiti/usacota.svg',
    maskPath: 'assets/circuiti/usacota_mask.png',
    xPercentage: 0.3,
    yPercentage: 0.5,
  ),
  Circuit(
    id: 'usamiami',
    displayName: 'USA Miami',
    svgPath: 'assets/circuiti/usamiami.svg',
    maskPath: 'assets/circuiti/usamiami_mask.png',
    xPercentage: 0.3,
    yPercentage: 0.5,
  ),
  Circuit(
    id: 'usavegas',
    displayName: 'USA Vegas',
    svgPath: 'assets/circuiti/usavegas.svg',
    maskPath: 'assets/circuiti/usavegas_mask.png',
    xPercentage: 0.3,
    yPercentage: 0.5,
  ),
];
