name: Build Windows EXE and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Windows (Release)
        run: flutter build windows --release

      - name: Archive Windows Release folder
        shell: pwsh
        run: |
          $ReleasePath = "build/windows/x64/runner/Release"
          $ZipPath = "build/windows/F1-ProjectGame-windows-release.zip"
          if (!(Test-Path $ReleasePath)) { throw "Release folder not found: $ReleasePath" }
          if (Test-Path $ZipPath) { Remove-Item $ZipPath }
          Compress-Archive -Path "$ReleasePath/*" -DestinationPath $ZipPath
          Write-Host "Created archive at $ZipPath"

      - name: Upload artifact (Windows zip)
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: build/windows/F1-ProjectGame-windows-release.zip

      - name: Create Release and Upload Windows zip
        uses: softprops/action-gh-release@v2
        with:
          files: build/windows/F1-ProjectGame-windows-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}