name: Build Windows EXE and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Windows (Release)
        run: flutter build windows --release

      - name: Zip Windows Release folder
        shell: pwsh
        run: |
          $ReleaseDir = "build/windows/x64/runner/Release"
          $ZipPath = "build/windows/F1ProjectGame-Windows.zip"
          Compress-Archive -Path "$ReleaseDir/*" -DestinationPath $ZipPath -Force

      - name: Upload artifact (ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: build/windows/F1ProjectGame-Windows.zip

      - name: Create Release and Upload ZIP
        uses: softprops/action-gh-release@v2
        with:
          files: build/windows/F1ProjectGame-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}